// Code generated by mockery v2.31.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IAuthenticationController is an autogenerated mock type for the IAuthenticationController type
type IAuthenticationController struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx
func (_m *IAuthenticationController) Login(ctx *gin.Context) {
	_m.Called(ctx)
}

// Register provides a mock function with given fields: ctx
func (_m *IAuthenticationController) Register(ctx *gin.Context) {
	_m.Called(ctx)
}

// NewIAuthenticationController creates a new instance of IAuthenticationController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthenticationController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthenticationController {
	mock := &IAuthenticationController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
