// Code generated by mockery v2.31.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ICommentController is an autogenerated mock type for the ICommentController type
type ICommentController struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *ICommentController) Create(ctx *gin.Context) {
	_m.Called(ctx)
}

// Find provides a mock function with given fields: ctx
func (_m *ICommentController) Find(ctx *gin.Context) {
	_m.Called(ctx)
}

// UserDelete provides a mock function with given fields: ctx
func (_m *ICommentController) UserDelete(ctx *gin.Context) {
	_m.Called(ctx)
}

// NewICommentController creates a new instance of ICommentController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICommentController(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICommentController {
	mock := &ICommentController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
