// Code generated by mockery v2.31.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IFfmpeg is an autogenerated mock type for the IFfmpeg type
type IFfmpeg struct {
	mock.Mock
}

// Convert provides a mock function with given fields: targetPath, outputFileName
func (_m *IFfmpeg) Convert(targetPath string, outputFileName string) error {
	ret := _m.Called(targetPath, outputFileName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(targetPath, outputFileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIFfmpeg creates a new instance of IFfmpeg. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFfmpeg(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFfmpeg {
	mock := &IFfmpeg{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
