// Code generated by mockery v2.9.6. DO NOT EDIT.

package mocks

import (
	register "github.com/raaaaaaaay86/go-project-structure/domain/context/auth"
	mock "github.com/stretchr/testify/mock"
)

// IRegister is an autogenerated mock type for the IRegister type
type IRegister struct {
	mock.Mock
}

// Execute provides a mock function with given fields: command
func (_m *IRegister) Execute(command register.RegisterUserCommand) (*register.RegisterUserResponse, error) {
	ret := _m.Called(command)

	var r0 *register.RegisterUserResponse
	if rf, ok := ret.Get(0).(func(register.RegisterUserCommand) *register.RegisterUserResponse); ok {
		r0 = rf(command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*register.RegisterUserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(register.RegisterUserCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIRegister interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRegister creates a new instance of IRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRegister(t mockConstructorTestingTNewIRegister) *IRegister {
	mock := &IRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
