// Code generated by mockery v2.9.6. DO NOT EDIT.

package mocks

import (
	create "github.com/raaaaaaaay86/go-project-structure/domain/context/media/video"
	mock "github.com/stretchr/testify/mock"
)

// IVideoCreateCQRS is an autogenerated mock type for the IVideoCreateCQRS type
type IVideoCreateCQRS struct {
	mock.Mock
}

// Execute provides a mock function with given fields: cmd
func (_m *IVideoCreateCQRS) Execute(cmd create.CreateVideoCommand) (*create.CreateVideoResponse, error) {
	ret := _m.Called(cmd)

	var r0 *create.CreateVideoResponse
	if rf, ok := ret.Get(0).(func(create.CreateVideoCommand) *create.CreateVideoResponse); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*create.CreateVideoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(create.CreateVideoCommand) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIVideoCreateCQRS interface {
	mock.TestingT
	Cleanup(func())
}

// NewIVideoCreateCQRS creates a new instance of IVideoCreateCQRS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIVideoCreateCQRS(t mockConstructorTestingTNewIVideoCreateCQRS) *IVideoCreateCQRS {
	mock := &IVideoCreateCQRS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
