// Code generated by mockery v2.31.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IVideoController is an autogenerated mock type for the IVideoController type
type IVideoController struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *IVideoController) Create(ctx *gin.Context) {
	_m.Called(ctx)
}

// LikeVideo provides a mock function with given fields: ctx
func (_m *IVideoController) LikeVideo(ctx *gin.Context) {
	_m.Called(ctx)
}

// UnLikeVideo provides a mock function with given fields: ctx
func (_m *IVideoController) UnLikeVideo(ctx *gin.Context) {
	_m.Called(ctx)
}

// Upload provides a mock function with given fields: ctx
func (_m *IVideoController) Upload(ctx *gin.Context) {
	_m.Called(ctx)
}

// NewIVideoController creates a new instance of IVideoController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIVideoController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IVideoController {
	mock := &IVideoController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
