http:
  port: 8080

postgres:
  host: localhost
  port: 5432
  user: root
  password: 123456
  schema: video

mongodb:
  host: mongo1
  port: 27017
  user: root
  password: 123456

neo4j:
  uri: neo4j://localhost:7688
  user: neo4j
  password: 12345678

jaeger:
  endpoint: http://localhost:14268/api/traces

bucketPath:
  raw: /Users/linjiafu/project/go-video-demo/bucket
  converted: /Users/linjiafu/project/go-video-demo/bucket/converted